on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # You can adjust the schedule as needed. This one runs daily at midnight.

jobs:
  fetch-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Fetch repository status
        run: python .github/scripts/fetch_repo_status.py
        
      - name: Commit and push changes
        uses: endormi/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          email: "test@github-email-com.com"
          name: "GitHub Action"
          commit_message: "Update repository"
          branch: main
